### ISSUE TITLE
CapstoneJavascript 

### ISSUE THREAD

**Issue by cvalencia1991** [kal2944/Javascript-capstone-project#21]
GitHub Link: https://github.com/kal2944/Javascript-capstone-project.git

We are going to work with 2 people 
# Kalkidan and Cesar
this project is for 2 teammates

**Comment by Reem-lab** [comment]
# Hi Team, 👋🏻 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights ✨
- Great on set up the Kanban ✅
- Great job dividing that tasks and the time ✅

## Required Changes ♻️
_Check the comments under the review._
- [x] I think it would be a great if you assign each task to each person so kindly assign the tasks between you that you be fair anough and clear to both of you ✅✨🚀

## You can just press on the task and choose from assigners who want to assign this task to? 🚀☺

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by cvalencia1991** [comment]
Ok i added each  number of each task assing us to the project also added in the kandboard

**Comment by prolajumokeoni** [comment]
Hi @Team
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights 
✔️  Good issue Description

 ## Required Changes ♻️

- [ ] Just as the previous reviewer requested, kindly assign cards to team members, All cards with `group task` in the title should also be assigned to someone, see screenshot below ⬇️ 

 
<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/69638013/196296390-4b5102e9-e844-434f-87b0-803dd2e13b61.png">
 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Kindly  decide who is Student A, or  Student B. So each card with Student A in its title should always be assigned to the same student (and analogical for student B)
- Kindly add the correct link to your GitHub project(kanban board) in the issue created above 👍🏿 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by cvalencia1991** [comment]
Ok we assign the Group task of each person who is going to work with

**Comment by codecaiine** [comment]
Hi @kal2944 @cvalencia1991 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good issue Description :heavy_check_mark: 
- Great partners assigned :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
